config/routes.rb
Blogger::Application.routes.draw do
	
	root to: 'articles#index'
	
	get 'tags/:tag', to: 'articles#index', as: :tag

  
  resources :articles do
  	resources :comments
	end
  
	resources :articles
	
	resources :authors
	
	resources :author_sessions, only: [ :new, :create, :destroy ]

	get 'login'  => 'author_sessions#new'
	get 'logout' => 'author_sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	
	has_attached_file :image
	validates_attachment_size :image, :less_than => 5.megabytes
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	
	acts_as_taggable   
  acts_as_taggable_on :tag_list
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper


	def index
		if params[:tag]
		  @articles = Article.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 10)
		else
		  @articles = Article.paginate(page: params[:page], per_page: 10)
		end
	end
  
  def show
  	@article = Article.find(params[:id])
  	@comment = Comment.new
		@comment.article_id = @article.id
  end
  
  def new
  	@article = Article.new
  end
  
  def create
 		@article = Article.new(article_params)
	  @article.save
	  
	  flash.notice = "Congratulations! you created a new article named '#{@article.title}' !"
	  
	  redirect_to article_path(@article)
  end
  
  def destroy
  	@article = Article.find(params[:id])
  	@article.destroy
  	
  	flash.notice = "Successfully deleted the article named '#{@article.title}' !"
  	
  	redirect_to articles_path
  end
  
  def edit
  	@article = Article.find(params[:id])
	end
	
	def update
		@article = Article.find(params[:id])
		@article.update(article_params)
		
		flash.notice = "You just updated the article '#{@article.title}' !"
		
		redirect_to article_path(@article)
	end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_to(articles_path, message: 'Logged in successfully.')
    else
      flash.notice = "Login failed! Please check email or password"
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, message: 'Logged out!')
  end
  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  
  before_filter :require_login, except: [:new, :create]
  
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created. Please click on the LOGIN link below' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
  	@comment = Comment.new(comment_params)
  	@comment.article_id = params[:article_id]
	
  	@comment.save
	
  	redirect_to article_path(@comment.article)
	end

	def comment_params
  	params.require(:comment).permit(:author_name, :body)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def article_params
  	params.require(:article).permit(:title, :body, :tag_list, :image)
	end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h6>Comment by <%= comment.author_name %></h6>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
  <br />
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  
  <p>
    <%= f.label :tag_list, "Tags (seperated by commas)" %>
    <br />
    <%= f.text_field :tag_list %>
  </p>
	
	<p>
		<% if @article.image.exists? %>
		    <%= image_tag @article.image.url %><br/>
		<% end %>
		<%= f.label :image, "Attach a New Image" %><br />
		<%= f.file_field :image %>
	</p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>List of Articles</h1>

<div id="tag_cloud">
	<% tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

<br /><br />

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article),
       class: 'article_title', id: "article_#{article.id}" %>
       <br />
       <p>Tags: <%= raw article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
    </li>
  <% end %>
  <br /><br />
	<%= will_paginate @articles %>
  <br />
  <% if logged_in? %>
  <%= link_to "Create a New Article", new_article_path, class: "new_article" %>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h2>Create a New Article</h2>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>

<p><%= image_tag @article.image.url %></p>

<p><%= @article.body %></p><br /><br /><br />

<% if logged_in? %>
	<%= link_to "edit", edit_article_path(@article) %>
<% end %>
&nbsp;
<% if logged_in? %>
	<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}%> <br />
<% end %>

<h4>Comments (<%= @article.comments.size %>)</h4>
<%= render partial: 'articles/comment', collection: @article.comments %>

<%= render partial: 'comments/form' %>

<%= link_to "Back to Articles List", articles_path %>

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h5>Post a Comment</h5>
<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="container">
    <div id="content">
    <p class="flash"><%= flash.notice %></p>
      <%= yield %>
      <hr>
      <h6>
        <% if logged_in? %>
          <%= "Logged in as #{current_user.email}" %>
          <%= link_to "(logout)", logout_path %>
        <% else %>
          <%= link_to "(Login)", login_path %>
          &nbsp;
          <%= link_to "(Sign Up)", new_author_path %>
        <% end %>
      </h6>
    </div>
  </div>
</body>


</html>